/**
 * fund — disperse Sepolia ETH from the deployer to the four agent accounts (§1.5).
 *
 * Idempotent top-up: each role has a TARGET balance; this sends only the shortfall,
 * so re-running after a partial run (or after a slash) tops back up without
 * over-funding. On first run it also GENERATES any missing agent keys and persists
 * them to the git-ignored `.env` (secrets are written to file, never printed).
 *
 * Requires `DEPLOYER_KEY` in `.env` (the Phase-1 deployer; holds Sepolia ETH).
 *
 *   pnpm fund
 */
import { readFileSync, writeFileSync, existsSync, appendFileSync } from "node:fs";
import { resolve } from "node:path";
import { formatEther } from "viem";
import { generatePrivateKey } from "viem/accounts";
import type { Address } from "viem";

import { publicClient, makeIdentity, STAKE, FEE } from "@proof/agents";

import { loadEnv, KEYS, requireEnv, ROOT, addrLink, txLink, banner, sleep } from "./_env.js";

/** Gas headroom for a handful of txs on Arbitrum Sepolia (cheap). */
const GAS_BUFFER = 1_500_000_000_000_000n; // 0.0015 ETH

/** Target end-balance per role: stake/fee obligations + gas. */
const TARGETS: Record<string, bigint> = {
  [KEYS.providerHonest]: STAKE + GAS_BUFFER, // register + commits
  [KEYS.providerCheat]: STAKE + GAS_BUFFER, // register (re-stake after slash) + commits
  [KEYS.buyer]: FEE + GAS_BUFFER, // deposit + finalize
  [KEYS.challenger]: GAS_BUFFER, // openChallenge + resolve (bounty refills it)
};

const ENV_FILE = resolve(ROOT, ".env");

/** Generate any missing agent key and persist it to `.env` (without printing it). */
function ensureKeys(): void {
  if (!existsSync(ENV_FILE)) writeFileSync(ENV_FILE, "# Generated by scripts/fund.ts — git-ignored, do not commit.\n");
  const existing = readFileSync(ENV_FILE, "utf8");
  for (const name of Object.values(KEYS)) {
    const cur = process.env[name];
    if (cur && cur !== "0x") continue; // already set in shell or .env
    if (new RegExp(`^${name}=0x[0-9a-fA-F]{64}`, "m").test(existing)) continue;
    const pk = generatePrivateKey();
    appendFileSync(ENV_FILE, `${name}=${pk}\n`);
    process.env[name] = pk;
    console.log(`generated ${name} → persisted to .env`);
  }
}

async function main(): Promise<void> {
  loadEnv();
  banner("fund — deployer → agent accounts (Arbitrum Sepolia)");

  const deployer = makeIdentity(requireEnv("DEPLOYER_KEY"));
  const deployerBal = await publicClient.getBalance({ address: deployer.address });
  console.log(`deployer   ${deployer.address}  ${formatEther(deployerBal)} ETH`);

  ensureKeys();
  loadEnv(); // pick up any freshly-generated keys

  // Compute shortfalls first so we can sanity-check the deployer can cover them.
  const plan: { name: string; address: Address; topUp: bigint; target: bigint }[] = [];
  for (const [name, target] of Object.entries(TARGETS)) {
    const address = makeIdentity(requireEnv(name)).address as Address;
    const bal = await publicClient.getBalance({ address });
    const topUp = bal >= target ? 0n : target - bal;
    plan.push({ name, address, topUp, target });
  }

  const totalOut = plan.reduce((s, p) => s + p.topUp, 0n);
  banner("plan");
  for (const p of plan) {
    const have = p.target - p.topUp;
    console.log(
      `${p.name.padEnd(20)} ${p.address}  have ${formatEther(have)} → target ${formatEther(p.target)}` +
        (p.topUp > 0n ? `  (+${formatEther(p.topUp)})` : "  (ok)")
    );
  }
  console.log(`\ntotal to send: ${formatEther(totalOut)} ETH`);

  if (totalOut === 0n) {
    console.log("\nAll accounts already at target. Nothing to do.");
    return;
  }
  if (deployerBal < totalOut + GAS_BUFFER) {
    throw new Error(
      `deployer balance ${formatEther(deployerBal)} ETH < required ${formatEther(totalOut + GAS_BUFFER)} ETH — fund the deployer first`
    );
  }

  banner("sending");
  for (const p of plan) {
    if (p.topUp === 0n) continue;
    const hash = await deployer.wallet.sendTransaction({
      account: deployer.account,
      chain: deployer.wallet.chain,
      to: p.address,
      value: p.topUp,
    });
    await publicClient.waitForTransactionReceipt({ hash });
    console.log(`→ ${p.name.padEnd(20)} +${formatEther(p.topUp)} ETH  ${txLink(hash)}`);
    await sleep(500); // avoid nonce races on flaky public RPCs
  }

  banner("✅ funded");
  console.log("Recipients:");
  for (const p of plan) console.log(`  ${p.name.padEnd(20)} ${addrLink(p.address)}`);
  console.log("\nNext: `pnpm fund-check` → `pnpm seed` → `pnpm e2e:happy` → `pnpm e2e:cheat`.");
}

main().catch((err) => {
  console.error("\n❌ fund failed:\n", err);
  process.exit(1);
});
